# Development Prometheus Configuration
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: 'randevubu-development'
    replica: '1'

scrape_configs:
  # RandevuBu Application (Development)
  - job_name: 'randevubu-dev'
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  # Health endpoint monitoring
  - job_name: 'randevubu-health'
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s