import { PrismaClient, DiscountType } from '@prisma/client';

const prisma = new PrismaClient();

async function seedComprehensiveDiscountCodes() {
  console.log('🎫 Seeding comprehensive discount codes with all types...');

  // Clear existing discount codes
  await prisma.discountCodeUsage.deleteMany();
  await prisma.discountCode.deleteMany();

  const now = new Date();
  const nextMonth = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  const nextYear = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000);

  // Get all subscription plans to use in applicable plans
  const plans = await prisma.subscriptionPlan.findMany();
  const allPlanIds = plans.map(plan => plan.id);
  const premiumPlanIds = plans.filter(plan => 
    plan.name.toLowerCase().includes('premium') || 
    plan.name.toLowerCase().includes('professional') ||
    plan.name.toLowerCase().includes('business') ||
    plan.name.toLowerCase().includes('enterprise') ||
    plan.name.toLowerCase().includes('standart')
  ).map(plan => plan.id);
  const basicPlanIds = plans.filter(plan => 
    plan.name.toLowerCase().includes('basic') || 
    plan.name.toLowerCase().includes('starter') ||
    plan.name.toLowerCase().includes('baslangic')
  ).map(plan => plan.id);

  const discountCodes = [
    // ========================================
    // ONE-TIME DISCOUNT CODES
    // ========================================

    // 1. Welcome Discount (One-time, Percentage)
    {
      id: `dc_welcome_${Date.now()}`,
      code: 'WELCOME20',
      name: 'New Customer Welcome',
      description: 'Welcome discount for new customers - 20% off first payment',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 20.0,
      maxUsages: 1000,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'welcome',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        description: 'Welcome offer for new signups - one-time only'
      }
    },

    // 2. Early Bird Special (One-time, Percentage, Limited Time)
    {
      id: `dc_early_${Date.now()}`,
      code: 'EARLY50',
      name: 'Early Bird Special',
      description: 'Limited time early bird discount - 50% off first payment',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 50.0,
      maxUsages: 100,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextMonth,
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'limited_time',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        urgency: 'high'
      }
    },

    // 3. Fixed Amount Discount (One-time, Fixed Amount)
    {
      id: `dc_save100_${Date.now()}`,
      code: 'SAVE100',
      name: 'Save 100 TL',
      description: 'Save 100 TL on your first payment',
      discountType: DiscountType.FIXED_AMOUNT,
      discountValue: 100.0,
      maxUsages: 200,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 500.0,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'fixed_discount',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        billingType: 'any'
      }
    },

    // 4. Flash Sale (One-time, High Percentage, Very Limited)
    {
      id: `dc_flash_${Date.now()}`,
      code: 'FLASH60',
      name: 'Flash Sale',
      description: 'Flash sale - 60% off first payment! Limited time only',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 60.0,
      maxUsages: 25,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000), // 2 days
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'flash_sale',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        urgency: 'extreme',
        promotion_type: 'flash'
      }
    },

    // ========================================
    // RECURRING DISCOUNT CODES
    // ========================================

    // 5. Loyalty Reward (Recurring, 3 payments)
    {
      id: `dc_loyal_${Date.now()}`,
      code: 'LOYAL35',
      name: 'Loyalty Reward',
      description: 'Thank you for your loyalty - 35% off for 3 payments',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 35.0,
      maxUsages: 100,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 150.0,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'loyalty',
        isRecurring: true,
        maxRecurringUses: 3,
        autoGenerated: false,
        targetAudience: 'returning_customers'
      }
    },

    // 6. Premium Upgrade (Recurring, 2 payments)
    {
      id: `dc_upgrade_${Date.now()}`,
      code: 'UPGRADE25',
      name: 'Premium Upgrade',
      description: 'Upgrade to premium plans with 25% off for 2 payments',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 25.0,
      maxUsages: 500,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 100.0,
      applicablePlans: premiumPlanIds,
      metadata: {
        category: 'upgrade',
        isRecurring: true,
        maxRecurringUses: 2,
        autoGenerated: false,
        targetAudience: 'existing_users'
      }
    },

    // 7. Student Discount (Recurring, 6 payments)
    {
      id: `dc_student_${Date.now()}`,
      code: 'STUDENT50',
      name: 'Student Discount',
      description: 'Special discount for students - 50% off for 6 payments',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 50.0,
      maxUsages: 500,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: null,
      applicablePlans: basicPlanIds,
      metadata: {
        category: 'education',
        isRecurring: true,
        maxRecurringUses: 6,
        autoGenerated: false,
        targetAudience: 'students',
        verificationRequired: true
      }
    },

    // 8. VIP Customer (Recurring, 4 payments)
    {
      id: `dc_vip_${Date.now()}`,
      code: 'VIP30',
      name: 'VIP Customer Exclusive',
      description: 'Exclusive discount for VIP customers - 30% off for 4 payments',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 30.0,
      maxUsages: 50,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 200.0,
      applicablePlans: premiumPlanIds,
      metadata: {
        category: 'vip',
        isRecurring: true,
        maxRecurringUses: 4,
        autoGenerated: false,
        exclusivity: 'high',
        targetAudience: 'vip_customers'
      }
    },

    // ========================================
    // SPECIAL SCENARIO DISCOUNT CODES
    // ========================================

    // 9. Holiday Special (One-time, High Percentage, Short Duration)
    {
      id: `dc_holiday_${Date.now()}`,
      code: 'HOLIDAY40',
      name: 'Holiday Special',
      description: 'Holiday season special offer - 40% off first payment',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 40.0,
      maxUsages: 300,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000), // 7 days
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'seasonal',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        urgency: 'high',
        season: 'holiday'
      }
    },

    // 10. Referral Bonus (One-time, Percentage)
    {
      id: `dc_refer_${Date.now()}`,
      code: 'REFER15',
      name: 'Referral Bonus',
      description: 'Referral program bonus - 15% off first payment for referred customers',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 15.0,
      maxUsages: 1000,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'referral',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        source: 'referral_program'
      }
    },

    // 11. Trial Extension (One-time, Fixed Amount)
    {
      id: `dc_trial_${Date.now()}`,
      code: 'TRIAL50',
      name: 'Trial Extension',
      description: 'Extend your trial with 50 TL off first payment',
      discountType: DiscountType.FIXED_AMOUNT,
      discountValue: 50.0,
      maxUsages: 200,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 100.0,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'trial_extension',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        targetAudience: 'trial_users'
      }
    },

    // 12. Annual Commitment (Recurring, 12 payments)
    {
      id: `dc_annual_${Date.now()}`,
      code: 'ANNUAL20',
      name: 'Annual Commitment',
      description: 'Commit to annual billing with 20% off for 12 payments',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 20.0,
      maxUsages: 100,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 500.0,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'annual_commitment',
        isRecurring: true,
        maxRecurringUses: 12,
        autoGenerated: false,
        billingType: 'annual'
      }
    },

    // ========================================
    // EDGE CASE DISCOUNT CODES
    // ========================================

    // 13. Expired Discount (For Testing)
    {
      id: `dc_expired_${Date.now()}`,
      code: 'EXPIRED10',
      name: 'Expired Discount',
      description: 'This discount has expired - for testing purposes',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 10.0,
      maxUsages: 100,
      currentUsages: 0,
      isActive: false, // Inactive
      validFrom: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
      validUntil: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'test',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        status: 'expired'
      }
    },

    // 14. Usage Limit Reached (For Testing)
    {
      id: `dc_limited_${Date.now()}`,
      code: 'LIMITED5',
      name: 'Limited Usage',
      description: 'This discount has reached its usage limit - for testing purposes',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 5.0,
      maxUsages: 1,
      currentUsages: 1, // Already used
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: null,
      applicablePlans: allPlanIds,
      metadata: {
        category: 'test',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        status: 'usage_limit_reached'
      }
    },

    // 15. Minimum Purchase Required (For Testing)
    {
      id: `dc_minimum_${Date.now()}`,
      code: 'MINIMUM25',
      name: 'Minimum Purchase Required',
      description: 'Requires minimum purchase of 1000 TL - for testing purposes',
      discountType: DiscountType.PERCENTAGE,
      discountValue: 25.0,
      maxUsages: 50,
      currentUsages: 0,
      isActive: true,
      validFrom: now,
      validUntil: nextYear,
      minPurchaseAmount: 1000.0, // High minimum
      applicablePlans: allPlanIds,
      metadata: {
        category: 'test',
        isRecurring: false,
        maxRecurringUses: 1,
        autoGenerated: false,
        status: 'minimum_purchase_required'
      }
    }
  ];

  console.log(`Creating ${discountCodes.length} comprehensive discount codes...`);

  for (const discountCode of discountCodes) {
    await prisma.discountCode.create({
      data: discountCode
    });
    console.log(`✅ Created discount code: ${discountCode.code} (${discountCode.name})`);
  }

  // Create some sample usage records (for demonstration)
  console.log('Creating sample usage records...');

  // Get the first admin user (if exists) to attribute codes to
  const adminUser = await prisma.user.findFirst();

  if (adminUser) {
    // Mark some codes as used
    const welcomeCode = await prisma.discountCode.findUnique({
      where: { code: 'WELCOME20' }
    });

    if (welcomeCode) {
      // Create a sample usage
      await prisma.discountCodeUsage.create({
        data: {
          id: `dcu_${Date.now()}_sample`,
          discountCodeId: welcomeCode.id,
          userId: adminUser.id,
          discountAmount: 20.0,
          originalAmount: 100.0,
          finalAmount: 80.0,
          metadata: {
            sampleUsage: true,
            planName: 'Basic Plan',
            paymentType: 'trial_conversion'
          }
        }
      });

      console.log('✅ Created sample usage record for WELCOME20');
    }
  }

  const totalCodes = await prisma.discountCode.count();
  const activeCodes = await prisma.discountCode.count({ where: { isActive: true } });
  const totalUsages = await prisma.discountCodeUsage.count();

  console.log(`\n🎫 Comprehensive discount codes seeded successfully!`);
  console.log(`   Total codes: ${totalCodes}`);
  console.log(`   Active codes: ${activeCodes}`);
  console.log(`   Sample usages: ${totalUsages}`);
  
  console.log(`\n💡 Available discount code types:`);
  console.log(`   📊 ONE-TIME DISCOUNTS:`);
  console.log(`   • WELCOME20 - 20% off first payment (Welcome)`);
  console.log(`   • EARLY50 - 50% off first payment (Early Bird)`);
  console.log(`   • SAVE100 - 100 TL off first payment (Fixed Amount)`);
  console.log(`   • FLASH60 - 60% off first payment (Flash Sale)`);
  console.log(`   • HOLIDAY40 - 40% off first payment (Holiday Special)`);
  console.log(`   • REFER15 - 15% off first payment (Referral Bonus)`);
  console.log(`   • TRIAL50 - 50 TL off first payment (Trial Extension)`);
  
  console.log(`\n   🔄 RECURRING DISCOUNTS:`);
  console.log(`   • LOYAL35 - 35% off for 3 payments (Loyalty Reward)`);
  console.log(`   • UPGRADE25 - 25% off for 2 payments (Premium Upgrade)`);
  console.log(`   • STUDENT50 - 50% off for 6 payments (Student Discount)`);
  console.log(`   • VIP30 - 30% off for 4 payments (VIP Customer)`);
  console.log(`   • ANNUAL20 - 20% off for 12 payments (Annual Commitment)`);
  
  console.log(`\n   🧪 TEST DISCOUNTS:`);
  console.log(`   • EXPIRED10 - Expired discount (Testing)`);
  console.log(`   • LIMITED5 - Usage limit reached (Testing)`);
  console.log(`   • MINIMUM25 - High minimum purchase (Testing)`);
  
  console.log(`\n🎯 Discount Code Categories:`);
  console.log(`   • Welcome & Onboarding`);
  console.log(`   • Limited Time Offers`);
  console.log(`   • Loyalty & Retention`);
  console.log(`   • Upgrade Incentives`);
  console.log(`   • Seasonal Promotions`);
  console.log(`   • Referral Programs`);
  console.log(`   • Educational Discounts`);
  console.log(`   • VIP & Exclusive Offers`);
  console.log(`   • Annual Commitments`);
  console.log(`   • Test & Edge Cases`);
}

export default seedComprehensiveDiscountCodes;

// If this file is run directly, execute the seeding
if (require.main === module) {
  seedComprehensiveDiscountCodes()
    .catch((e) => {
      console.error('❌ Error seeding comprehensive discount codes:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}



